-- +goose Up
-- +goose StatementBegin

CREATE TABLE IF NOT EXISTS web.gallery_category (
                                                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                    parent_id INTEGER REFERENCES web.gallery_category(id) ON DELETE CASCADE,
                                                    code TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS web.gallery_category_translation (
                                                                category_id INTEGER NOT NULL REFERENCES web.gallery_category(id) ON DELETE CASCADE,
                                                                locale TEXT NOT NULL CHECK (locale IN ('ru', 'en', 'fr')),
                                                                title TEXT NOT NULL,
                                                                slug TEXT NOT NULL,
                                                                description TEXT NOT NULL DEFAULT '',

                                                                PRIMARY KEY (category_id, locale),
                                                                UNIQUE (locale, slug)
);

CREATE TABLE IF NOT EXISTS web.gallery_photo (
                                                 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                 category_id INTEGER NOT NULL REFERENCES web.gallery_category(id) ON DELETE CASCADE,
                                                 object_key TEXT NOT NULL,
                                                 sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS web.gallery_photo_translation (
                                                             photo_id INTEGER NOT NULL REFERENCES web.gallery_photo(id) ON DELETE CASCADE,
                                                             locale TEXT NOT NULL CHECK (locale IN ('ru', 'en', 'fr')),
                                                             caption TEXT,

                                                             PRIMARY KEY (photo_id, locale)
);

CREATE INDEX IF NOT EXISTS idx_gallery_photo_category_id
    ON web.gallery_photo (category_id);

CREATE INDEX IF NOT EXISTS idx_gallery_photo_category_id_sort_order
    ON web.gallery_photo (category_id, sort_order);

CREATE INDEX IF NOT EXISTS idx_gallery_category_parent_id
    ON web.gallery_category (parent_id);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

DROP INDEX IF EXISTS idx_gallery_category_parent_id;
DROP INDEX IF EXISTS idx_gallery_photo_category_id;
DROP INDEX IF EXISTS idx_gallery_photo_category_id_sort_order;

DROP TABLE IF EXISTS web.gallery_photo_translation;
DROP TABLE IF EXISTS web.gallery_photo;
DROP TABLE IF EXISTS web.gallery_category_translation;
DROP TABLE IF EXISTS web.gallery_category;

-- +goose StatementEnd