// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type WebMenuItem struct {
	ID        pgtype.UUID
	Position  int16
	Label     string
	Icon      string
	Url       string
	IsActive  bool
	CreatedAt time.Time
}

type WebSession struct {
	ID        string
	UserID    pgtype.UUID
	ExpiresAt time.Time
	CreatedAt time.Time
}

type WebUser struct {
	ID        pgtype.UUID
	Email     string
	Password  string
	FullName  pgtype.Text
	Role      string
	CreatedAt time.Time
}
