// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type WebSession struct {
	ID        string
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type WebUser struct {
	ID        pgtype.UUID
	Email     string
	Password  string
	FullName  pgtype.Text
	Role      string
	CreatedAt pgtype.Timestamptz
}
