// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdminIfNotExist = `-- name: CreateAdminIfNotExist :exec
INSERT INTO web.users (email, password, role, full_name)
VALUES ($1, $2, 'admin', 'System Administrator')
    ON CONFLICT (email) DO NOTHING
`

type CreateAdminIfNotExistParams struct {
	Email    string
	Password string
}

func (q *Queries) CreateAdminIfNotExist(ctx context.Context, arg CreateAdminIfNotExistParams) error {
	_, err := q.db.Exec(ctx, createAdminIfNotExist, arg.Email, arg.Password)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO web.sessions (id, user_id, expires_at)
VALUES ($1, $2, $3)
    RETURNING id, user_id, expires_at, created_at
`

type CreateSessionParams struct {
	ID        string
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (WebSession, error) {
	row := q.db.QueryRow(ctx, createSession, arg.ID, arg.UserID, arg.ExpiresAt)
	var i WebSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, full_name, role, created_at FROM web.users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (WebUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i WebUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.FullName,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserBySessionID = `-- name: GetUserBySessionID :one
SELECT u.id, u.email, u.password, u.full_name, u.role, u.created_at
  FROM web.users u
       JOIN web.sessions s
         ON s.user_id = u.id
WHERE s.id = $1 AND s.expires_at > NOW()
`

func (q *Queries) GetUserBySessionID(ctx context.Context, id string) (WebUser, error) {
	row := q.db.QueryRow(ctx, getUserBySessionID, id)
	var i WebUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.FullName,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
